spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 513607975763-ckfoe9j1hc73feh78svnr1jcrlnao4g3.apps.googleusercontent.com
            client-secret: KZScMyzd0Y7TyjrKqprntdMd
  data:
    mongodb:
      uri: mongodb+srv://m001-student:T3amS0ftwar3!@team-software-5cubw.azure.mongodb.net/test?retryWrites=true
      database: GathR
server:
  port: 8443
  ssl:
    key-store-type: PKCS12
    key-store: src/main/resources/keystore/keystoreAE.p12
    key-store-password: T3amS0ftwar3!
    key-alias: keystoreAE
    trust-store: src/main/resources/keystore/keystoreAE.p12
    trust-store-password: T3amS0ftwar3!
    
